### ISSUE TITLE
some errors about environment

### ISSUE THREAD

**Issue by Jzian** [naokiyokoyama/ovon#18]
Hi, what an amazing work! I got some issues when I try to reproduce the method. 

Traceback (most recent call last):
  File "/home/robotic/miniconda3/envs/ovon/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/robotic/miniconda3/envs/ovon/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/robotic/miniconda3/envs/ovon/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/robotic/buildspace/habitat-lab/habitat-lab/habitat/core/vector_env.py", line 251, in _worker_env
    env = EnvCountEpisodeWrapper(EnvObsDictWrapper(env_fn(*env_fn_args)))
  File "/home/robotic/buildspace/habitat-lab/habitat-lab/habitat/utils/pickle5_multiprocessing.py", line 100, in __call__
    return self.fn(*args, **kwargs)
  File "/home/robotic/buildspace/habitat-lab/habitat-lab/habitat/utils/gym_definitions.py", line 53, in make_gym_from_config
    env_class=env_class, config=config
  File "/home/robotic/buildspace/habitat-lab/habitat-lab/habitat/utils/env_utils.py", line 31, in make_env_fn
    dataset = make_dataset(config.dataset.type, config=config.dataset)
  File "/home/robotic/buildspace/habitat-lab/habitat-lab/habitat/datasets/registration.py", line 22, in make_dataset
    return _dataset(**kwargs)  # type: ignore
  File "/home/robotic/workspace/ovon/ovon/dataset/ovon_dataset.py", line 96, in __init__
    super().__init__(config)
  File "/home/robotic/buildspace/habitat-lab/habitat-lab/habitat/datasets/pointnav/pointnav_dataset.py", line 123, in __init__
    self.from_json(f.read(), scenes_dir=config.scenes_dir)
  File "/home/robotic/miniconda3/envs/ovon/lib/python3.7/gzip.py", line 287, in read
    return self._buffer.read(size)
  File "/home/robotic/miniconda3/envs/ovon/lib/python3.7/gzip.py", line 474, in read
    if not self._read_gzip_header():
  File "/home/robotic/miniconda3/envs/ovon/lib/python3.7/gzip.py", line 422, in _read_gzip_header
    **raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'\x00\x05')**

ConnectionResetError: [Errno 104] Connection reset by peer
Exception ignored in: <function VectorEnv.__del__ at 0x79ee3c4aea70>
Traceback (most recent call last):
  File "/home/robotic/buildspace/habitat-lab/habitat-lab/habitat/core/vector_env.py", line 589, in __del__
    self.close()
  File "/home/robotic/buildspace/habitat-lab/habitat-lab/habitat/core/vector_env.py", line 457, in close
    read_fn()
  File "/home/robotic/buildspace/habitat-lab/habitat-lab/habitat/core/vector_env.py", line 108, in __call__
    res = self.read_fn()
  File "/home/robotic/buildspace/habitat-lab/habitat-lab/habitat/utils/pickle5_multiprocessing.py", line 68, in recv
    buf = self.recv_bytes()
  File "/home/robotic/miniconda3/envs/ovon/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/robotic/miniconda3/envs/ovon/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/robotic/miniconda3/envs/ovon/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    **raise EOFError
EOFError:**

**Comment by rginjapan** [comment]
hi, did you solve the issue?

**Comment by qwer137559** [comment]
i  have same issue ,did you solve the issue?

**Comment by Grady10086** [comment]
i have the same issue,did u solve it
